### ISSUE TITLE
rotationsx and quaternionsx import each other

### ISSUE THREAD

**Issue by mattjhill** [spacetelescope/jwst_gtvt#1]
This causes an error in Python 2.7
```
Traceback (most recent call last):
  File "jwst_gtvt", line 5, in <module>
    from jwst_gtvt.find_tgt_info import main
  File "/users/joana/.local/lib/python2.7/site-packages/jwst_gtvt-0.0.1-py2.7.egg/jwst_gtvt/find_tgt_info.py", line 7, in <module>
    from . import ephemeris_old2x as EPH
  File "/users/joana/.local/lib/python2.7/site-packages/jwst_gtvt-0.0.1-py2.7.egg/jwst_gtvt/ephemeris_old2x.py", line 9, in <module>
    from .rotationsx import *
  File "/users/joana/.local/lib/python2.7/site-packages/jwst_gtvt-0.0.1-py2.7.egg/jwst_gtvt/rotationsx.py", line 10, in <module>
    from . import quaternionx as quat
  File "/users/joana/.local/lib/python2.7/site-packages/jwst_gtvt-0.0.1-py2.7.egg/jwst_gtvt/quaternionx.py", line 29, in <module>
    from . import rotationsx as rot
ImportError: cannot import name rotationsx
```

**Comment by mattjhill** [comment]
Fixed in #2
